### PR TITLE
Mention and link to Code of Conduct

### PR DESCRIPTION
**Pull request by Bravepeanut**
Added a note and link to the Contributor Covenant Code of Conduct

### CODE REVIEW

**Comment by Bravepeanut** [comment]
Please let me know if I did everything right. With this only being my second pull request, I'm loving all feedback!

**Comment by ffrank** [comment]
Thanks, this is a great initiative.

Please note that we [adapted](https://github.com/puppet-community/code-of-conduct) the CoC and essentially maintain a fork. I assume it would make sense to link that instead.

Pinging @daenney - thoughts on this?

While we're taking wishes ;-) I would love a PR against https://github.com/puppet-community/puppet-community.github.io to link the CoC on the website.

**Comment by daenney** [comment]
It's not really a fork. The only thing we changed is how we prefer people to raise issues with us. The rest is carbon copy.

**Comment by igalic** [comment]
we can totes "fork" it, to describe, as @daenney mentions, how to raise issues.
we can do this in a second iteration, though, and for now merge @Bravepeanut's pr

**Comment by ffrank** [comment]
And done. Thanks for the contribution!

**Comment by igalic** [comment]
\o/ thanks @Bravepeanut!

**Comment by nibalizer** [comment]
Thanks!

**Pull request merged**
