### PR TITLE
#15 Changed the link to the code of conduct for pupet

### LINKED ISSUE #15: explicitly mention and link our Code of Conduct
We are using the [Contributor Covenant](http://contributor-covenant.org/) code of conduct, and should explicitly [link](http://contributor-covenant.org/version/1/2/0/) to it in our [CONTRIBUTING.md](https://github.com/puppet-community/modulesync_config/blob/master/moduleroot/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by blacktoko**
Fixes #15 Linked to the specific code of conduct from the puppet-community repo. Adapted from http://contributor-covenant.org/version/1/2/0/

### CODE REVIEW

**Comment by ffrank** [comment]
Neat, thanks!

Could you amend your commit and have the message start with `(#15)`, then `push -f` to your branch again? This aids book-keeping wrt. the github issues.

**Comment by blacktoko** [comment]
Should i recommit the change with the new message in a new pull request? (sorry if this is a obviouse question but this is the first time i am doing this).

**Comment by igalic** [comment]
@blacktoko no need to create a new pull request.
after changing the commit message with [git commit --ammend](https://www.git-scm.com/docs/git-commit), just run [git push --force](https://www.git-scm.com/docs/git-push), as @ffrank suggests!

**Comment by blacktoko** [comment]
Thanks for your help and the link about the flow! I will study it :-)

**Pull request merged**
