### PR TITLE
(maint) Add ability to override the Gemfile on dependency modules

### PR DESCRIPTION
**Pull request by cyberious**
- Use pattern established by puppetlabs and specify our defaults
  in the config default rather than hard coding the Gemfile

### CODE REVIEW

**Comment by blkperl** [comment]
:-1:  This increases the code complexity

**Comment by igalic** [comment]
it's probably the right path, but i'm not happy with the test failures…

should we exclude the gemfile?

**Comment by cyberious** [comment]
@blkperl we are either going to manage the Gemfile or have a bunch of modules we don't manage it on resulting in different patterns. I would rather have the complexity here than to have snowflakes everywhere. This is more relevant when talking about mixing modules for Windows and Linux systems where the dependencies vary.

**Comment by cyberious** [comment]
@igalic I will look into the failures

**Comment by igalic** [comment]
@cyberious :+1: for adding complexity in :one: place.

:bomb: :snowflake:

**Comment by igalic** [comment]
fixed by #37!
thanks @cyberious && @jyaworski!

**Pull request closed without merging**
