### PR TITLE
Use puppet-lint from github

### PR DESCRIPTION
**Pull request by alexjfisher**
There hasn't be a release for a *long* time, but there have been some
fixes since then.

### CODE REVIEW

**Comment by cyberious** [comment]
My only concern is that how do we determine breaking changes, I think it would be better if we can get @rodjek to ship a new release if one is needed with semvar

**Comment by alexjfisher** [comment]
A new release would be better, but I'm not expecting one any time soon. :(
https://github.com/rodjek/puppet-lint/issues/401
https://github.com/rodjek/puppet-lint/issues/443

rspec-puppet is set to the latest git version even though there have been new releases of that.
https://github.com/puppet-community/modulesync_config/blob/master/config_defaults.yml#L20

For puppet-lint at least, how about fixing on the latest commit instead? https://github.com/rodjek/puppet-lint/commit/2546fed6be894bbcff15c3f48d4b6f6bc15d94d1

**Comment by cyberious** [comment]
Commented on it as well, perhaps it is time for PuppetLabs to step up and take over it.

**Comment by igalic** [comment]
@alexjfisher this needs a rebase now, although, i think it might already be merged in a different pr

**Comment by juniorsysadmin** [comment]
:+1:

**Pull request merged**
